name: tan_shomiti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  patrol: ^3.15.2
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
